# fly.toml app configuration file generated for barrage-chatroom on 2023-09-08T20:00:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "barrage-chatroom"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
