# fly.toml app configuration file generated for barrage-chat on 2023-09-09T14:25:47+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "barrage-chat"
primary_region = "sin"

[build]

[env]
  PORT = "4000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

